# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:12
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='main_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=rooms.models.random_filename),
        ),
    ]
