# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20161026_2312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([]),
        ),
    ]
