# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 17:46
from __future__ import unicode_literals

from django.contrib.auth.models import Group
from django.db import migrations

from forrent.settings import HOSTS_GROUP_NAME, GUESTS_GROUP_NAME


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name=HOSTS_GROUP_NAME)
    Group.objects.get_or_create(name=GUESTS_GROUP_NAME)


class Migration(migrations.Migration):
    dependencies = [

    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
