# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 09:54
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations


def create_admin(apps, schema_editor):
    admin_user, created = User.objects.get_or_create(username='admin')
    admin_user.set_password('admin')
    admin_user.is_superuser = True
    admin_user.is_staff = True
    admin_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
