# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 23:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('accommodates', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('private_bathroom', models.BooleanField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_since', models.DateField()),
                ('available_to', models.DateField()),
                ('main_photo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'room amenities',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='amenity_set',
            field=models.ManyToManyField(blank=True, to='rooms.RoomAmenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('host', 'name')]),
        ),
    ]
