# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 09:29
from __future__ import unicode_literals

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from forrent.settings import HOSTS_GROUP_NAME


def set_permission(codename, name):
    (content_type, created,) = ContentType.objects.get_or_create(
        app_label='rooms', model='room'
    )
    (permission, created,) = Permission.objects.get_or_create(
        content_type=content_type, codename=codename, name=name,
    )
    (hosts_group, created,) = Group.objects.get_or_create(name=HOSTS_GROUP_NAME)
    hosts_group.permissions.add(permission)


def set_room_permissions(apps, schema_editor):
    set_permission(codename='add_room', name='Can add room')
    set_permission(codename='change_room', name='Can change room')
    set_permission(codename='delete_room', name='Can delete room')


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_room_permissions),
    ]
